# spring.datasource.url=jdbc:h2:file:./target/h2db/db/mobilesearch;DB_CLOSE_DELAY=-1
# spring.datasource.data-username=3011
# spring.datasource.data-password=3011
spring:
  datasource:
    url: jdbc:h2:file:./target/h2db/db/mobilesearch;DB_CLOSE_DELAY=-1
    username: 3011
    password: 3011
  h2: 
    console:
      enabled: true
  jpa:
    database: H2
    show-sql: true
