spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mobilesearch?useSSL=false&serverTimezone=Hongkong&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 3011
    password: 3011